### ISSUE TITLE
'tqdmm' object has no attribute 'leave'

### ISSUE THREAD

**Issue by cchikis** [wimpomp/parfor#2]
When attempting to run the example on in readme, I produce the following error.

from time import sleep
from parfor import parfor
@parfor(range(10), (3,))
def fun(i, a):
    sleep(1)
    return a*i**2
print(fun)

  File "<ipython-input-29-965bd1bff26a>", line 3, in <module>
    @parfor(range(10), (3,))

  File "---/parfor/__init__.py", line 234, in decfun
    return pmap(fun, *args, **kwargs)

  File "---/parfor/__init__.py", line 483, in pmap
    return [p[i] for i in range(length)] #collect the results

  File "---/parfor/__init__.py", line 149, in __exit__
    if not self.leave:

AttributeError: 'tqdmm' object has no attribute 'leave'

**Comment by wimpomp** [comment]
Thanks for the report. It turns out that it doesn't work in combination with older versions of tqdm. I have updated the requirements for parfor and installation/upgrade with pip should take care of this now.

**Comment by cchikis** [comment]
Thank you!
